//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inward_Tapal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public long ChequeNo { get; set; }
        public Nullable<int> CQNO { get; set; }
        public string TPLNO { get; set; }
        public Nullable<System.DateTime> CQDATE { get; set; }
        public string BANK { get; set; }
        public string AMOUNT { get; set; }
    }
}
