//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inward_Tapal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Id { get; set; }
        public string Dept { get; set; }
        public string Dept_Code { get; set; }
        public string DeptOrCentre { get; set; }
    }
}
