//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inward_Tapal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inward
    {
        public long Id { get; set; }
        public string TPLNO { get; set; }
        public string T_Sno { get; set; }
        public string T_From { get; set; }
        public string T_Dept { get; set; }
        public string T_Subject { get; set; }
        public string T_Subject_Value { get; set; }
        public string T_Section { get; set; }
        public string T_User { get; set; }
        public string T_Passout { get; set; }
        public string T_Cheque { get; set; }
        public System.DateTime Date_in { get; set; }
        public string wfcpno { get; set; }
        public bool Issue { get; set; }
        public string IssueName { get; set; }
    }
}
