//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inward_Tapal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string Emp_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Section { get; set; }
        public string Designation { get; set; }
    }
}
