//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inward_Tapal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public long Subject_Id { get; set; }
        public string Subject_Name { get; set; }
    }
}
